name: check_wasm
description: "Check if WASM is correctly configured. Checks if WASM version is loaded and multiheading is supported."
version: 0.0.3
homepage: https://github.com/Gerrel/check_wasm

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  web: ">=1.1.1<2.0.0"
  http: ">=1.5.0<2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
